#!/bin/bash
clang++ -O2 -Iabseil-cpp -std=c++1z -Wall -Werror -Wextra entity.cpp game.cpp geo.cpp main.cpp abseil-cpp/absl/hash/internal/city.cc abseil-cpp/absl/hash/internal/hash.cc abseil-cpp/absl/hash/internal/low_level_hash.cc abseil-cpp/absl/base/internal/raw_logging.cc abseil-cpp/absl/base/internal/throw_delegate.cc abseil-cpp/absl/container/internal/raw_hash_set.cc
